name: Node.js Package

on:
  push:
    branches: [master]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Check out the repo
       uses: actions/checkout@v2
     - name: Build and Publish head Docker image
       uses: VaultVulp/gp-docker-action@1.1.7
       with:
          github-token: ${{ secrets.TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
          image-name: jmsth-docker # Provide Docker image name
          image-tag: head # Provide Docker image tag 
